"""initial schema

Revision ID: 184582787968
Revises: 
Create Date: 2026-04-11 15:39:48.613048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '184582787968'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('horses',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('blood_reg_num', sa.String(length=10), nullable=False),
    sa.Column('name_kana', sa.String(length=36), nullable=True),
    sa.Column('name_eng', sa.String(length=60), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('coat_color', sa.SmallInteger(), nullable=True),
    sa.Column('father_name', sa.String(length=36), nullable=True),
    sa.Column('father_code', sa.String(length=10), nullable=True),
    sa.Column('mother_name', sa.String(length=36), nullable=True),
    sa.Column('mother_code', sa.String(length=10), nullable=True),
    sa.Column('mother_father', sa.String(length=36), nullable=True),
    sa.Column('mother_father_code', sa.String(length=10), nullable=True),
    sa.Column('producer_name', sa.String(length=60), nullable=True),
    sa.Column('area_name', sa.String(length=20), nullable=True),
    sa.Column('owner_name', sa.String(length=60), nullable=True),
    sa.Column('total_wins', sa.SmallInteger(), nullable=False),
    sa.Column('total_races', sa.SmallInteger(), nullable=False),
    sa.Column('total_earnings', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blood_reg_num')
    )
    op.create_index('idx_horses_father', 'horses', ['father_code'], unique=False)
    op.create_index('idx_horses_mother_father', 'horses', ['mother_father_code'], unique=False)
    op.create_table('jockeys',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('jockey_code', sa.String(length=5), nullable=False),
    sa.Column('name_kanji', sa.String(length=20), nullable=True),
    sa.Column('name_kana', sa.String(length=30), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('belong_code', sa.SmallInteger(), nullable=True),
    sa.Column('total_1st', sa.Integer(), nullable=False),
    sa.Column('total_2nd', sa.Integer(), nullable=False),
    sa.Column('total_3rd', sa.Integer(), nullable=False),
    sa.Column('total_races', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jockey_code')
    )
    op.create_table('jvlink_sync_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('dataspec', sa.String(length=4), nullable=False),
    sa.Column('last_timestamp', sa.String(length=14), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataspec')
    )
    op.create_table('races',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_key', sa.String(length=16), nullable=False),
    sa.Column('race_date', sa.Date(), nullable=False),
    sa.Column('venue_code', sa.String(length=2), nullable=False),
    sa.Column('kai', sa.SmallInteger(), nullable=False),
    sa.Column('nichi', sa.SmallInteger(), nullable=False),
    sa.Column('race_num', sa.SmallInteger(), nullable=False),
    sa.Column('race_name', sa.String(length=60), nullable=True),
    sa.Column('race_name_sub', sa.String(length=60), nullable=True),
    sa.Column('grade', sa.SmallInteger(), nullable=True),
    sa.Column('distance', sa.SmallInteger(), nullable=False),
    sa.Column('track_type', sa.SmallInteger(), nullable=False),
    sa.Column('track_dir', sa.SmallInteger(), nullable=True),
    sa.Column('horse_count', sa.SmallInteger(), nullable=True),
    sa.Column('weather', sa.SmallInteger(), nullable=True),
    sa.Column('track_cond', sa.SmallInteger(), nullable=True),
    sa.Column('condition_code', sa.SmallInteger(), nullable=True),
    sa.Column('is_female_only', sa.Boolean(), nullable=False),
    sa.Column('is_mixed', sa.Boolean(), nullable=False),
    sa.Column('is_handicap', sa.Boolean(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.Column('prize_1st', sa.Integer(), nullable=True),
    sa.Column('prize_2nd', sa.Integer(), nullable=True),
    sa.Column('prize_3rd', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_key')
    )
    op.create_index('idx_races_date', 'races', ['race_date'], unique=False)
    op.create_index('idx_races_grade', 'races', ['grade'], unique=False)
    op.create_index('idx_races_track', 'races', ['track_type', 'distance'], unique=False)
    op.create_index('idx_races_venue', 'races', ['venue_code', 'race_date'], unique=False)
    op.create_table('trainers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('trainer_code', sa.String(length=5), nullable=False),
    sa.Column('name_kanji', sa.String(length=20), nullable=True),
    sa.Column('name_kana', sa.String(length=30), nullable=True),
    sa.Column('belong_code', sa.SmallInteger(), nullable=True),
    sa.Column('total_1st', sa.Integer(), nullable=False),
    sa.Column('total_races', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trainer_code')
    )
    op.create_table('horse_weights',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('horse_num', sa.SmallInteger(), nullable=False),
    sa.Column('weight', sa.SmallInteger(), nullable=True),
    sa.Column('weight_diff', sa.SmallInteger(), nullable=True),
    sa.Column('announced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_num', name='uq_weight_race_horse')
    )
    op.create_table('payouts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('bet_type', sa.SmallInteger(), nullable=False),
    sa.Column('combination', sa.String(length=20), nullable=False),
    sa.Column('payout', sa.Integer(), nullable=False),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'bet_type', 'combination', name='uq_payout')
    )
    op.create_index('idx_payouts_race', 'payouts', ['race_id'], unique=False)
    op.create_table('race_entries',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('horse_id', sa.BigInteger(), nullable=True),
    sa.Column('jockey_id', sa.BigInteger(), nullable=True),
    sa.Column('trainer_id', sa.BigInteger(), nullable=True),
    sa.Column('horse_num', sa.SmallInteger(), nullable=False),
    sa.Column('frame_num', sa.SmallInteger(), nullable=False),
    sa.Column('weight_carry', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('age', sa.SmallInteger(), nullable=True),
    sa.Column('sex', sa.SmallInteger(), nullable=True),
    sa.Column('horse_weight', sa.SmallInteger(), nullable=True),
    sa.Column('weight_diff', sa.SmallInteger(), nullable=True),
    sa.Column('odds_win', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('odds_place_min', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('odds_place_max', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.Column('finish_order', sa.SmallInteger(), nullable=True),
    sa.Column('finish_time', sa.Integer(), nullable=True),
    sa.Column('last_3f', sa.Integer(), nullable=True),
    sa.Column('margin', sa.SmallInteger(), nullable=True),
    sa.Column('corner_1', sa.SmallInteger(), nullable=True),
    sa.Column('corner_2', sa.SmallInteger(), nullable=True),
    sa.Column('corner_3', sa.SmallInteger(), nullable=True),
    sa.Column('corner_4', sa.SmallInteger(), nullable=True),
    sa.Column('abnormal_code', sa.SmallInteger(), nullable=True),
    sa.Column('speed_index', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['jockey_id'], ['jockeys.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.ForeignKeyConstraint(['trainer_id'], ['trainers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'horse_num', name='uq_race_horse')
    )
    op.create_index('idx_entries_finish', 'race_entries', ['finish_order'], unique=False)
    op.create_index('idx_entries_horse', 'race_entries', ['horse_id'], unique=False)
    op.create_index('idx_entries_jockey', 'race_entries', ['jockey_id'], unique=False)
    op.create_index('idx_entries_race', 'race_entries', ['race_id'], unique=False)
    op.create_index('idx_entries_speed', 'race_entries', ['speed_index'], unique=False)
    op.create_table('race_laps',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=False),
    sa.Column('hallon_order', sa.SmallInteger(), nullable=False),
    sa.Column('lap_time', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('race_id', 'hallon_order', name='uq_lap')
    )
    op.create_index('idx_laps_race', 'race_laps', ['race_id'], unique=False)
    op.create_table('training_times',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('horse_id', sa.BigInteger(), nullable=False),
    sa.Column('race_id', sa.BigInteger(), nullable=True),
    sa.Column('training_date', sa.Date(), nullable=False),
    sa.Column('weeks_before', sa.SmallInteger(), nullable=True),
    sa.Column('course_type', sa.SmallInteger(), nullable=True),
    sa.Column('distance', sa.SmallInteger(), nullable=True),
    sa.Column('lap_time', sa.Integer(), nullable=True),
    sa.Column('last_3f', sa.Integer(), nullable=True),
    sa.Column('last_1f', sa.Integer(), nullable=True),
    sa.Column('rank', sa.String(length=1), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['horse_id'], ['horses.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['races.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_training_horse_date', 'training_times', ['horse_id', 'training_date'], unique=False)
    op.create_index('idx_training_race', 'training_times', ['race_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('entry_id', sa.BigInteger(), nullable=False),
    sa.Column('snapshot_type', sa.SmallInteger(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.Column('odds_win', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('odds_place_min', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('odds_place_max', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('popularity', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['race_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'snapshot_type', name='uq_odds_snapshot')
    )
    op.create_index('idx_odds_entry', 'odds_snapshots', ['entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_odds_entry', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index('idx_training_race', table_name='training_times')
    op.drop_index('idx_training_horse_date', table_name='training_times')
    op.drop_table('training_times')
    op.drop_index('idx_laps_race', table_name='race_laps')
    op.drop_table('race_laps')
    op.drop_index('idx_entries_speed', table_name='race_entries')
    op.drop_index('idx_entries_race', table_name='race_entries')
    op.drop_index('idx_entries_jockey', table_name='race_entries')
    op.drop_index('idx_entries_horse', table_name='race_entries')
    op.drop_index('idx_entries_finish', table_name='race_entries')
    op.drop_table('race_entries')
    op.drop_index('idx_payouts_race', table_name='payouts')
    op.drop_table('payouts')
    op.drop_table('horse_weights')
    op.drop_table('trainers')
    op.drop_index('idx_races_venue', table_name='races')
    op.drop_index('idx_races_track', table_name='races')
    op.drop_index('idx_races_grade', table_name='races')
    op.drop_index('idx_races_date', table_name='races')
    op.drop_table('races')
    op.drop_table('jvlink_sync_log')
    op.drop_table('jockeys')
    op.drop_index('idx_horses_mother_father', table_name='horses')
    op.drop_index('idx_horses_father', table_name='horses')
    op.drop_table('horses')
    # ### end Alembic commands ###
