"""add start_time and se_extension fields

Revision ID: d3d69b761711
Revises: 4fd05a0334cd
Create Date: 2026-04-12 17:29:47.600267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd3d69b761711'
down_revision: Union[str, None] = '4fd05a0334cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pedigree_lineages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pedigree_lineages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.add_column('race_entries', sa.Column('blinker_code', sa.SmallInteger(), nullable=True))
    op.add_column('race_entries', sa.Column('prev_jockey_code', sa.String(length=5), nullable=True))
    op.add_column('race_entries', sa.Column('prev_weight_carry', sa.Numeric(precision=4, scale=1), nullable=True))
    op.add_column('race_entries', sa.Column('apprentice_code', sa.SmallInteger(), nullable=True))
    op.add_column('race_entries', sa.Column('belong_region', sa.SmallInteger(), nullable=True))
    op.add_column('races', sa.Column('start_time', sa.String(length=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('races', 'start_time')
    op.drop_column('race_entries', 'belong_region')
    op.drop_column('race_entries', 'apprentice_code')
    op.drop_column('race_entries', 'prev_weight_carry')
    op.drop_column('race_entries', 'prev_jockey_code')
    op.drop_column('race_entries', 'blinker_code')
    op.alter_column('pedigree_lineages', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('pedigree_lineages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###
